---
title: "3. Social dominance and steepness 2"
author: "Justin Varholick"
date: '2022-06-15'
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#plots
library(tidyverse)
library(ggplot2)
library(ggbeeswarm)
library(ggsci)
library(ggpubr)
library(ggstance)
library(cowplot)
library(readxl)
library(patchwork)
```

## Social dominance status data
```{r}
ind_rank_wins <- read.csv("/Users/justinvarholick/Documents/GitHub/AcomysDominance_2022_Data_Results/Data/winsbyanimal.csv")
ind_rank_wins <- ind_rank_wins[,2:6]
ind_rank_wins <- rename(ind_rank_wins, "Cage"="Cage.x")
sex_id <- read_excel("/Users/justinvarholick/Documents/GitHub/AcomysDominance_2022_Data_Results/Data/AcomysDomRegen_Inventory.xlsx", sheet = "Sheet3")
sex_id$Cage <- as.factor(sex_id$Cage)
ind_rank_wins$Cage <- as.factor(ind_rank_wins$Cage)
ind_rank_wins <- left_join(ind_rank_wins, sex_id, by="Cage")

ind_ds <- read.csv("/Users/justinvarholick/Documents/GitHub/AcomysDominance_2022_Data_Results/Data/dscorebyanimal_edited.csv")
ind_ds$Cage <- as.factor(ind_ds$Cage)
ind_ds <- left_join(ind_ds, ind_rank_wins, by=c("AnimalID"="Opponent.1"))
ind_ds$dom_status_ds <- as.factor(ind_ds$dom_status_ds)

dc_cage <- read.csv("/Users/justinvarholick/Documents/GitHub/AcomysDominance_2022_Data_Results/Data/dcbycage_edited.csv")
cages <- ind_ds %>% 
  select(Cage.x, DumCage, Sex, GrpSize, Age, Trt) %>% 
  distinct() %>% 
  rename(Cage=Cage.x)
dc_cage$Cage <- as.factor(dc_cage$Cage)
dc_cage <- left_join(dc_cage, cages, by="Cage")

stp <- read.csv("/Users/justinvarholick/Documents/GitHub/AcomysDominance_2022_Data_Results/Data/steepbycage_edited.csv")
stp$Cage <- as.factor(stp$Cage)
stp <- left_join(stp, ind_ds, by=c("Cage"="Cage.x"))
stp <- stp %>% 
  mutate(norm_ds=ds+(GrpSize*(GrpSize-1)/2))
```
##Social dominance graphs
```{r, david scores}
ds_plot <- ggplot(ind_ds, aes(as.factor(DumCage), ds, fill=ds, shape=dom_status_ds))+
  geom_point(aes(fill=ds), color="black", size=4)+
  scale_y_continuous(limits=c(-3,3), breaks=c(-3,-2,-1,0,1,2,3), expand=c(0,0))+
  scale_fill_gsea()+
  scale_shape_manual(values=c(21,24,22,23))+
  xlab("") + ylab("David's Score")+
  labs(fill="David's \nScore", shape="Dominance \nStatus")+
  theme_cowplot() + background_grid()
ds_plot
```
```{r, dc index}

dc_cage$Trt <- factor(dc_cage$Trt, levels=c("YFD", "YMD", "YMT", "OFD"))

dc_plot <- ggplot(dc_cage, aes(as.factor(DumCage), dc, fill=Trt))+
  geom_bar(stat="identity", color="black")+
  scale_y_continuous(expand=c(0,0))+
  scale_fill_npg()+
  ylab("DC index") + xlab("")+
  guides(fill=guide_legend("Housing Condition"))+
  theme_cowplot()
dc_plot
```
```{r grouped plot}
fig1 <- plot_grid(
  ds_plot, dc_plot,
  labels="AUTO", ncol=2
)

ggsave("/Users/justinvarholick/Documents/GitHub/AcomysDominance_2022_Data_Results/R generated figures/Fig1_plot.png", fig1, units="in", width = 9, height = 3, device='png', dpi=300)

fig1
```

##Analyses were done by hand in reference to Siegel and Castellan 1988, "Nonparametric Statistics for the Behavioral Sciences" pg 130