---
title: "3. Social dominance and steepness 2"
author: "Justin Varholick"
date: '2022-06-15'
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#plots
library(tidyverse)
library(ggplot2)
library(ggbeeswarm)
library(ggthemr) #devtools::install_github('Mikata-Project/ggthemr')
library(ggsci)
library(ggpubr)
library(ggstance)
library(cowplot)
library(readxl)
library(patchwork)

ggthemr('flat')
```

## Social dominance status data
```{r}
ind_rank_wins <- read.csv("/Users/justinvarholick/Documents/GitHub/AcomysDominance_2022_Data_Results/Data/winsbyanimal_edited.csv")
ind_rank_wins <- ind_rank_wins[,2:6]
ind_rank_wins <- rename(ind_rank_wins, "Cage"="Cage.x")
sex_id <- read_excel("/Users/justinvarholick/Documents/GitHub/AcomysDominance_2022_Data_Results/Data/AcomysDomRegen_Inventory.xlsx", sheet = "Sheet3")
sex_id$Cage <- as.factor(sex_id$Cage)
ind_rank_wins$Cage <- as.factor(ind_rank_wins$Cage)
ind_rank_wins <- left_join(ind_rank_wins, sex_id, by="Cage")

ind_ds <- read.csv("/Users/justinvarholick/Documents/GitHub/AcomysDominance_2022_Data_Results/Data/dscorebyanimal_edited.csv")
ind_ds$Cage <- as.factor(ind_ds$Cage)
ind_ds <- left_join(ind_ds, ind_rank, by=c("AnimalID"="Opponent.1"))
ind_ds$dom_status_ds <- as.factor(ind_ds$dom_status_ds)

stp <- read.csv("/Users/justinvarholick/Documents/GitHub/AcomysDominance_2022_Data_Results/Data/steepbycage_edited.csv")
stp$Cage <- as.factor(stp$Cage)
stp <- left_join(stp, ind_ds, by=c("Cage"="Cage.x"))
stp <- stp %>% 
  mutate(norm_ds=ds+(GrpSize*(GrpSize-1)/2))
```
## Social dominance graphs
```{r f ds}
sexdyads_f <- ind_ds %>% 
  filter(GrpSize==2) %>% 
  filter(Age=="Young") %>% 
  filter(Sex=="F")

status_plot_f <- ggplot(sexdyads_f, aes(as.factor(DumCage), ds, color=dom_status_ds, shape=dom_status_ds)) +
  geom_point(size=3, alpha=1) +
  xlab("")+ ylab("David's Score")+
  scale_color_manual(values=c("#E64B35B2", "#4DBBD5B2", "#00A087B2","#3C5488B2"))+
  scale_shape_manual(values=c(19,17,15,18))+
  guides(color="none", shape="none")+
  ggtitle("Young Female Dyads")
status_plot_f

```
```{r m ds}
sexdyads_m <- ind_ds %>% 
  filter(GrpSize==2) %>% 
  filter(Sex=="M")

status_plot_m <- ggplot(sexdyads_m, aes(as.factor(DumCage), ds, color=dom_status_ds, shape=dom_status_ds)) +
  geom_point(size=3, alpha=1) +
  xlab("")+ ylab("David's Score")+
  scale_color_manual(values=c("#E64B35B2", "#4DBBD5B2", "#00A087B2","#3C5488B2"))+
  scale_shape_manual(values=c(19,17,15,18))+
  guides(color="none", shape="none")+
  ggtitle("Young Male Dyads")
status_plot_m

```


```{r group ds}
grpsize_male_3 <- ind_ds %>% 
  filter(Sex=="M") %>% 
  filter(GrpSize=="3")

status_plot_3 <- ggplot(grpsize_male_3, aes(as.factor(DumCage), ds, color=dom_status_ds, shape=dom_status_ds)) +
  geom_point(size=3, alpha=1, position=position_dodge(width=0.5)) +
  xlab("")+ ylab("David's Score")+
  scale_color_manual(values=c("#E64B35B2", "#00A087B2", "#4DBBD5B2"))+
  scale_shape_manual(values=c(19,15,17))+
  guides(color="none", shape="none")+
  ggtitle("Young Male Triads")
status_plot_3
```

```{r age ds}
age_female_old <- ind_ds %>% 
  filter(Sex=="F") %>% 
  filter(Age=="Old")

status_plot_old <- ggplot(age_female_old, aes(as.factor(DumCage), ds, color=dom_status_ds, shape=dom_status_ds)) +
  geom_point(size=3, alpha=1) +
  xlab("")+ ylab("David's Score")+
  scale_color_manual(values="#3C5488B2")+
  scale_shape_manual(values=18)+
  guides(color="none", shape="none")+
  ggtitle("Old Female Dyads")
status_plot_old
```

```{r grouped plot}
fig1 <- plot_grid(
  status_plot_f, status_plot_m,
  status_plot_old, status_plot_3,
  labels = "AUTO", ncol = 2
)

ggsave("/Users/justinvarholick/Documents/GitHub/AcomysDominance_2022_Data_Results/R generated figures/Fig1_status_plots.tiff", fig1, units="cm", width = 15, height = 15, device='tiff', dpi=300)

 fig1
```

##Analyses were done by hand in reference to Siegel and Castellan 1988, "Nonparametric Statistics for the Behavioral Sciences" pg 130